apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-gl-saas-igcvbos3606xp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-gl-saas-igcvbos3606xp
    app.kubernetes.io/part-of: application-gl-saas-s2kg8c4p1e2sz
  name: component-gl-saas-igcvbos3606xp
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-gl-saas-igcvbos3606xp
status:
  loadBalancer: {}
